### PR TITLE
Delete osfile-perms.yml

### PR DESCRIPTION
**Pull request by disconnect3d**
The `osfile-perms.yml` rule currently suggests to apply more broad permissions to file/directory related operations, describing that the "umask is applied to perm".

The umask is a user-setting that may restrict the default permissions set when creating files or directories (through e.g. `open` or `mkdir` syscalls). Applying more broad permissions won't "cancel" the effect of umask. The umask will still be applied and if we want to enforce certain permissions, it seems one has to invoke (one of) the `chmod` syscalls, similarly to what the `mkdir` unix program does:

```
$ strace mkdir --mode=0777 test7
...
mkdir("test7", 0777)                    = 0
openat(AT_FDCWD, "test7", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_DIRECTORY) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
fchmod(3, 0777)                         = 0
...
```
vs
```
$ strace mkdir test8
...
mkdir("test8", 0777)                    = 0
...
```

Coming back to the main topic: suggesting devs to apply more broad permissions is bad. Allowing others to write to a file or directory may allow them to make the program process malicious files created by others that were not supposed to create them in the first place, but, were allowed to due to such suggestion.

### CODE REVIEW

**Comment by dgryski** [comment]
I'm fine with this.  As much as (in a general sense) it's better for programs to not dictate policy and leave those sorts of decisions to the user, we probably can't determine which calls should have tighter positions.  If somebody wanted the default permissions they'll call `Create()` or `Open()`.

/cc @jcorbin

**Comment by jcorbin** [comment]
So the problem more comes around `os.Mkdir` and `os.MkdirAll` which is the entry point for most folk when doing something as innocuous as "ensure parent directory exists" before an `os.Create`. The temptation for developers unfamiliar with systems programming, is to pass `0755` since that the directory mode they're most used to as a user. However this leads to programs that are subtly misbehaved in environments where the users wants or needs group writability on all newly created things.

In my experience / view, a majority of use cases only really concerned about "is the user/group/world allowed at all, or not?" and then the disposition of "what can the user/group/world do?" is usually something that some sort of operator (user, package integrator, or system admin care about). So some heuristics that drop out of that:
- for mkdir the most common mode should be `0777` ; more sensitive applications may want `0700` or `0770`
- for openfile the most common mode should be `0666` ; more sensitive applications may want `0600` or `0660`
- any mode being passed to mkdir or openfile that lacks the write bit in any non-zero field is probably over-specified
- any mode being passed to mkdir that lacks the execute bit in any non-zero field is a mistake
- rarer cases like "lacking the execute bit in a g/w field when the owner field has it set" like `0744` are also mistakes

Now, amdist all of that, what is possible in these semgrep yaml rule files X what has an acceptable precision / recall trade-off is something I can't really speak to ;-)

**Comment by dgryski** [comment]
Hmm... so maybe we keep the rule but move it into some appropriately named subdirectory where we keep rules with a less clear value proposition?

**Comment by jcorbin** [comment]
That could do, also splitting openfile / mkdir may make sense again, since mkdir is, I believe, more (ab)used than openfile, since most folk should use `os.Create` which correctly specifies `0666` to the openfile syscall.

Now I'm not saying that there are not security sensitive apps that need to specify something quirky where they control down to the write permission level between user/group/world entities; but those cases should be rare enough vs the benefit of guiding most non-sensitive apps into more correct edge-case behavior, that at least a warning should be generally applicable for most use cases.

**Comment by disconnect3d** [comment]
> However this leads to programs that are subtly misbehaved in environments where the users wants or needs group writability on all newly created things.

Well in such case the devs/users should fix/adjust the permissions as needed. Imho is better to have more strict then too broad permissions, especially when its not super hard to fix "too strict permission" and a "too broad" might cause risks.

Also, when one needs to share a given directory across e.g. different binaries which act on behalf different users (which is a good practice), most likely, groups and group permissions should be used.

> for mkdir the most common mode should be 0777 ; more sensitive applications may want 0700 or 0770

**It should definetely not be a "most common mode".** This might be convenient, but its something that asks for a disaster.
For example, the "write mode" allows to remove files in a given directory no matter if the user has access to those files or not. So here, a `testuser` can delete `dc` user's files which were accessible only by `dc` because they had a write permission in the `xxx` directory:

```
testuser@jhtc:/tmp$ id
uid=1005(testuser) gid=1005(testuser) groups=1005(testuser),27(sudo),108(lxd),120(libvirt)
testuser@jhtc:/tmp$ ls -la xxx
total 204
drwxrwxrwx  2 dc   dc     4096 Sep  8 18:58 .
drwxrwxrwt 81 root root 196608 Sep  8 18:39 ..
-rwx------  1 dc   dc        5 Sep  8 18:58 a
testuser@jhtc:/tmp$ cat xxx/a
cat: xxx/a: Permission denied
testuser@jhtc:/tmp$ rm -rf xxx/a
testuser@jhtc:/tmp$ ls -la xxx
total 200
drwxrwxrwx  2 dc   dc     4096 Sep  8 19:01 .
drwxrwxrwt 81 root root 196608 Sep  8 18:39 ..
```

> for openfile the most common mode should be 0666 ; more sensitive applications may want 0600 or 0660

**Yet, another NO.** The default mode should be to prevent access from other users (even when they are in the same group as we do), so it should _most likely_ be 0600. Otherwise, you are telling people that its ok to allow others read their files and they might unexpectedly leak sensitive information this way.

> any mode being passed to mkdir or openfile that lacks the write bit in any non-zero field is probably over-specified

Why? Those permissions bits have their purpose. Preventing user from writing to their own files might be counter-intuitive but it fills a great purpose: it may prevent bugs, e.g., when the app would allow remote clients to append to files on the app's behalf.

> any mode being passed to mkdir that lacks the execute bit in any non-zero field is a mistake

**Probably yes.** I haven't double checked that but I don't think many apps would want to be able to list file names in a directory but not have any other access there (according to https://unix.stackexchange.com/a/317446).

> rarer cases like "lacking the execute bit in a g/w field when the owner field has it set" like 0744 are also mistakes

Lacking the exec bit for files is a valid use case (see above) but I agree that it might not be for directories.

---

Anyway, ultimately, the question is what is the purpose of this repository and what do we (or rather, the author) expect from it.
I use the rules present here in order to find potential bugs in the code and I sometimes point out too broad permissions to others as there is often no point in setting them.

By the way, if we look for potential problematic code, the `MkdirAll` function is full of race conditions and not nice in the way that if the directory exists, it won't report any error and won't check if the permissions correspond to the expected ones. This is something I think should be spotted and reported with e.g. Semgrep rules :P.

**Comment by jcorbin** [comment]
In my view, we're talking at a bit of cross purposes here: I'm talking about what modes should get passed to low level syscalls like `os.OpenFile` and `os.Mkdir` ; not what the final mode on the created file / directory should be. Consider:
- the Go stdlib is on my side here: see [`os.Create`](https://golang.org/src/os/file.go?s=9329:9368#L305)
- so is python's equivalent [`os.makedirs`](https://github.com/python/cpython/blob/master/Lib/os.py#L200) ; Go lacks the ability to specify a non-zero default for an arg of course ;-)
- I'm fairly confident that we can find more examples in other stdlibs / runtimes for "What's the default file creation / directory creation mode?" coming back with `0666` / `0777` as the answer
- Go's just in an uncanny place, where it forces the developer to specify the mode ( especially for mkdir ), which tends towards over-specification by userspace code

**Pull request merged**
